### ISSUE TITLE
release assets are missing version number

### ISSUE THREAD

**Issue by tstack** [ttiimm/litho#1]
The assets attached to this release:

https://github.com/ttiimm/litho/releases/tag/v0.1.0-alpha

Don't have a version number in their file name, for example, `litho-x86_64-apple-darwin.tar.gz`.  [ripgrep](https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0) might be a good example to look as a reference.

**Comment by ttiimm** [comment]
Fixed in v0.1.1-alpha
