### ISSUE TITLE
release asset should have a wrapper directory

### ISSUE THREAD

**Issue by tstack** [ttiimm/litho#2]
Unpacking the macos tarball leaves just the binary in the current directory, which is impolite.  I would suggest adding a wrapper directory with the full release name and also include the README, NEWS, LICENSE, etc...  For example:

```
litho-0.1.0-x86_64-apple-darwin/README.md
litho-0.1.0-x86_64-apple-darwin/NEWS
litho-0.1.0-x86_64-apple-darwin/litho
```

Can I also suggest using a zip file for macos since it likes to gunzip, but not untar when downloaded through the browser.  I think zips are automatically unpacked.

**Comment by ttiimm** [comment]
Fixed in v0.1.1-alpha build
