### ISSUE TITLE
Force downloading of the original image size

### ISSUE THREAD

**Issue by ddellsperger** [ttiimm/litho#7]
The image size is limited in the sync to either 512 pixels tall or 512 pixels wide, this is the default for all google photos photos, you would need to add additional parameters to the URL to support the original size of the image. See the [available google documentation](https://developers.google.com/photos/library/guides/access-media-items#image-base-urls) on photo urls.

**Comment by ttiimm** [comment]
One thing to be aware of is that the API will only returned a JPG fascimile of the original photo. Apparently this is how the API is [currently designed](https://issuetracker.google.com/issues/112096115).
